# Generated by Django 5.2.5 on 2025-08-07 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.IntegerField(unique=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('billed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('insurer_name', models.CharField(db_index=True, max_length=255)),
                ('discharge_date', models.DateField()),
                ('is_flagged', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpt_codes', models.CharField(max_length=255)),
                ('denial_reason', models.TextField(blank=True, null=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='claims.claim')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='claims.claim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
